[project]
name = "ai-news-summarizer"
version = "0.1.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[project.entry-points."dagger.mod"]
main_object = "main:AiNewsSummarizer"